[package]
name = "tera-bracket-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1.15.0"
serde_json = "1.0.79"
serde = "1.0.136"